//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OduncKitapAspnetMVCWebSolution_BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitaplar()
        {
            this.OduncIslemler = new HashSet<OduncIslemler>();
        }
    
        public int Id { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public string KitapAdi { get; set; }
        public byte TurId { get; set; }
        public int YazarId { get; set; }
        public int SayfaSayisi { get; set; }
        public int StokAdeti { get; set; }
        public bool SilindiMi { get; set; }
        public string ResimLink { get; set; }
    
        public virtual Turler Turler { get; set; }
        public virtual Yazarlar Yazarlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OduncIslemler> OduncIslemler { get; set; }
    }
}
