//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OduncKitapAspnetMVCWebSolution_BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OduncIslemler
    {
        public int Id { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public int UyeId { get; set; }
        public int KitapId { get; set; }
        public int PersonelId { get; set; }
        public System.DateTime OduncAlinmaTarihi { get; set; }
        public System.DateTime OduncBitisTarihi { get; set; }
        public bool TeslimEttiMi { get; set; }
        public Nullable<System.DateTime> TeslimEttigiTarih { get; set; }
    
        public virtual Kitaplar Kitaplar { get; set; }
        public virtual Personeller Personeller { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
