//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OduncKitapAspnetMVCWebSolution_BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uyeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uyeler()
        {
            this.OduncIslemler = new HashSet<OduncIslemler>();
        }
    
        public int Id { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public string UyeAdi { get; set; }
        public string UyeSoyadi { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public bool SilindiMi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OduncIslemler> OduncIslemler { get; set; }
    }
}
